services:
  # Backend API service
  - type: web
    name: amrganainy-portfolio-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false # Set this manually in Render dashboard
      - key: JWT_SECRET
        sync: false # Set this manually in Render dashboard
      - key: FRONTEND_URL
        value: https://YOUR_DOMAIN.com # Replace with your domain
    autoDeploy: true
